add fsm
boskuv/Task-Manager pull request #9
Opened 2021-11-29 19:42 UTC by boskuv

2021-11-29 20:03 UTC, greybutton requested changes
Как-то странно называются события. Лучше использовать глагол, который описывает переход. return_to_dev подходит, а вот над остальными нужно подумать. Ивент это функция, название функции - глагол

2021-11-29 20:03 UTC, greybutton commented on app/models/task.rb
> +      transition %i[:new_task, :released] => :archived
проверь линтер

2021-11-30 16:26 UTC, boskuv commented on app/models/task.rb
> +      transition %i[:new_task, :released] => :archived
+

2021-11-30 17:25 UTC, greybutton requested changes

2021-11-30 17:25 UTC, greybutton commented on app/models/task.rb
> +      transition [:':in_qa,', :':in_code_review'] => :in_development
не валидная запись

2021-11-30 17:25 UTC, greybutton commented on app/models/task.rb
> +      transition [:':new_task,', :':released'] => :archived
не валидная запись

2021-11-30 17:40 UTC, boskuv commented on app/models/task.rb
> +      transition [:':in_qa,', :':in_code_review'] => :in_development
странно, rubucop сам подправил. Сейчас посмотрю.

2021-11-30 20:44 UTC, greybutton approved these changes

2021-12-02 09:33 UTC, merged